### ISSUE TITLE
Interested in Creating RequireJS support? 

### ISSUE THREAD

**Issue by Henryvw** [braintree/credit-card-type#10]
For those of us using RequireJS, support could be greatly appreciated! Cheers

**Comment by mrak** [comment]
For the time being we are reflecting our own development style (CommonJS). We have other open-source libraries that are AMD-compatible and will look into making this one, too, in the future.

Aside from lacking out-of-the-box AMD support, are you able to use this library in your toolchain?

**Comment by Henryvw** [comment]
Yes other than that, I think we would have been able to use it

**Comment by crookedneighbor** [comment]
For now, we've decided to not add built in AMD support. If someone wants to fork and maintain an AMD compatible version of the library, we're open to adding a link to it in the README.
