### ISSUE TITLE
Dankort is not recognized

### ISSUE THREAD

**Issue by DaSchTour** [braintree/credit-card-type#100]
### General information

* Library version: 
* Browser and OS 

### Issue description

I found this while using card-validator library. Dankort with IIN 5019 and 4571 is recognized as Maestro or Visa.

**Comment by crookedneighbor** [comment]
Can you provide us official bin documentation for Dankort? As far as I'm aware, Braintree doesn't process Daknort, so we don't have bin data for it.

**Comment by DaSchTour** [comment]
I'm not sure what you consider an official bin documentation. You can find several information about this IIN used by Dankort all over the internet but all of these doesn't look like official to me.

**Comment by mwinkelm** [comment]
@crookedneighbor Have a look at https://binlist.net/ (a card number type lookup service). Their default example is one with a Dankort Visa card.

**Comment by crookedneighbor** [comment]
We need official documentation from Dankort to add it to the library. Going to close this now, but if we can get official documentation for these bin ranges, happy to add it.

**Comment by jonasskafte** [comment]
Hi @crookedneighbor,

How about this documentation from Nets:

[https://shop.nets.eu/web/partners/test-cards](https://shop.nets.eu/web/partners/test-cards)

As you can see, they suggest a bin of '5019' for testing.

"Nets is behind the Dankort and E-Dankort and is the sole acquire who accepts these payment methods." – [https://www.dibspayment.com/nets-en](https://www.dibspayment.com/nets-en)

See also: [https://www.dibspayment.com/nets-en](https://en.wikipedia.org/wiki/Nets_Group)

I believe Braintree won't be able to offer Dankort payments (except Visa/Dankort?), but it would be great if it was at least a recognized payment method so that buyers could be given an error message explaining to them that the Dankort isn't an accepted payment method...

Hope this is useful and many thanks!

**Comment by crookedneighbor** [comment]
If you'd like to open a PR that adheres to the documentation, go ahead.

**Comment by jonasskafte** [comment]
Hi there @crookedneighbor,

Thanks for following up on this!

I would love it if I was able to create a PR for this, but I am not a developer and so I'm afraid that I am not able to make a concrete suggestion for how to implement the support of Dankort. However, I hope that supporting this request and sharing the documentation here is useful.

Many thanks and hope to see this in the future!

**Comment by crookedneighbor** [comment]
This is not a card type supported by Braintree, so it's not high on our priority list to include it in this module. However, if an outside contributor wants to add it, I'm happy to review it. Thanks so much for providing the context and documentation on the card type.

**Comment by crookedneighbor** [comment]
If someone wants to take another stab at opening a PR now that the Typescript migration for this library is complete, go for it.

It was started here, but was closed due to inactivity: https://github.com/braintree/credit-card-type/pull/106

**Comment by mahendraHegde** [comment]
@crookedneighbor  I'd like to work on it, if its not already been taken.

**Comment by crookedneighbor** [comment]
Go for it.

**Comment by crookedneighbor** [comment]
I'm going to close this for now. See my explanation here: https://github.com/braintree/credit-card-type/pull/125#issuecomment-804188093

Happy to revisit this in the future if official and comprehensive documentation can be provided for the card type.

**Comment by mahendraHegde** [comment]
Hey @crookedneighbor  It would have been great if you had made this decision before you asked me pick it up. Now it will discourage me from taking up any further issues from related repositories.

**Comment by jonasskafte** [comment]
Hi guys,

I'm from Denmark and am really happy to see this getting some attention – thank you @mahendraHegde!

Would it not be fairly simple/easy to just add both these two card types to your solution @mahendraHegde and then it could be approved? -sorry, I'm asking as I wouldn't know how to do it myself 😄 :

Dankort = 5019
VISA/Dankort = 4571

I am very confident that there is no such thing as a MasterCard/Dankort. So I don't know where this is coming from?:

_"...5019 is technically a card that should be cobranded with Mastercard."_ – https://github.com/braintree/credit-card-type/pull/125#issuecomment-804188093

Please also see:

- https://tech.dibspayment.com/D2/Toolbox/Test_information/Cards
- https://developer.bambora.com/europe/checkout/getting-started/test-your-setup

-as you'll see, these guys only refer to Dankort and VISA/Dankort. Nets (first link) is the issuer of all Dankorts and so it would be strange if they didn't mention anything about MasterCard/Dankort but still offered it.

Hope this is useful input and many thanks for all your efforts!

**Comment by crookedneighbor** [comment]
@mahendraHegde I understand, and I'm sorry. I should have looked at the previously submitted documentation closer before saying it was okay to open a PR. I apologize for wasting your time.



@jonasskafte The trouble is, Braintree doesn't support Dankort, so we don't have our own relationship with Nets, so we don't have a way to verify the the bin data. If we have official documentation for the bin ranges, we're happy to add them to this module, but without that, we're in too much danger of misidentifying cards and can't include it.

We either need official public documentation for the bin range, or for a representative from Nets to reach out to our support team (and reference this issue) with bin documentation. https://help.braintreepayments.com/

Also, just a reminder that this module has the ability to add and update card data: https://github.com/braintree/credit-card-type#adding-card-types

So any brands that you want to support that the module does not can still be added for your use case.

**Comment by jonasskafte** [comment]
Thanks @crookedneighbor! -all makes perfect sense 👍 

Last question – does this not count as official documentation from Nets?:

https://tech.dibspayment.com/D2/Toolbox/Test_information/Cards

[tech.dibspayment.com](https://tech.dibspayment.com/) is Nets' developer documentation site.

Thanks!

**Comment by crookedneighbor** [comment]
While it provides specific test cards and prefixes for testing, it does not actually confirm the bin ranges of the card types, as far as I could tell. It's possible I missed an explicit callout about that when I skimmed the page, so feel free to point it out to me if I missed it.

**Comment by jonasskafte** [comment]
OK. Thanks @crookedneighbor!

I've just reached out to Nets to see if they can help and referenced this conversation 🤞

**Comment by jonasskafte** [comment]
Hello everyone!

So Nets got back to me and said this:

> Thank you for reaching out to us. Unfortunately there's no official data on the requested range, therefore it is not obtainable. Please ask Braintree to reach out to Nets for more detailed information on data needed and description of use.

Which is quite funny, because I had asked them to get in touch with Braintree as you suggested @crookedneighbor 😆 

So unless either party gives in, I guess this will be the spinning wheel of death as Braintree want Nets to reach out and Nets want Braintree to reach out.

🙄 

PS. In case it's useful, here's Nets email adress: ecom-dk@nets.eu

**Comment by crookedneighbor** [comment]
> Thank you for reaching out to us. Unfortunately there's no official data on the requested range, therefore it is not obtainable.

I think this pretty much answers this, we can't support this in our client side library if the bin range is not publicly available. Not sure how us reaching out to Nets will improve on that. Very strange that they're being so cagey about this.
