### ISSUE TITLE
Adding Aura

### ISSUE THREAD

**Issue by Daniel4Digital** [braintree/credit-card-type#109]
Would be great to add Aura.

You can see here the bin and all other infos: https://gist.github.com/erikhenrique/5931368

best regards

**Comment by crookedneighbor** [comment]
Please provide official documentation for Aura. This has been requested in the past, but we had to deny the request because there was no official documentation for the Aura card range available.

**Comment by crookedneighbor** [comment]
FYI, you can add custom card types. See: https://github.com/braintree/credit-card-type#adding-card-types

**Comment by Cut-Guyo9b** [comment]
So exactly what do you need buy I need this credit card my bills are past due

**Comment by Daniel4Digital** [comment]
Can't find official documentation. Only the url I provided above.

This is what I will use to add Aura. I'm removing maestro too since I beleive maestro for creditCard is deprecated.

Vue.prototype.$creditCardType.removeCard(Vue.prototype.$creditCardType.types.MAESTRO);
Vue.prototype.$creditCardType.addCard({
  niceType: "Aura",
  type: "aura",
  patterns: [50],
  gaps: [4, 8, 12],
  lengths: [16],
  code: {
    name: "CVV",
    size: 3,
  },
});
