### ISSUE TITLE
I want help to add card flags

### ISSUE THREAD

**Issue by ThiagoFelippi** [braintree/credit-card-type#116]
### Add card flags

Hi! I have custom card flags and I can implement this on the credit card type. Then, in any element you will be able to add a class and the card flag will appear

If you like this suggestion tell me and I can implement this :smiley:

**Comment by crookedneighbor** [comment]
I'm not sure I understand what you're asking to add. Can you elaborate?

**Comment by ThiagoFelippi** [comment]
Hi! The idea was implementing the credit card network image, like mastercard, visa and others.
Like this:
![image](https://user-images.githubusercontent.com/62997534/96340056-c1467800-106e-11eb-8dfb-c69e57731d65.jpeg)
You understand now?

**Comment by crookedneighbor** [comment]
Thanks for the offer. We think that makes more sense as a UI module that consumes credit-card-type, rather than having that as a feature within credit-card-type.
