### ISSUE TITLE
Mastercard type returning as Maestro

### ISSUE THREAD

**Issue by navarrojandg** [braintree/credit-card-type#121]
### General information

- Library version: 9.1.0
- Browser and OS: Chrome 87.0.4280.88 (64-bit) on MacOS 11.1, NodeJS v12.16.1

### Issue description

[Ayden docs](https://docs.adyen.com/development-resources/test-cards/test-card-numbers#mastercard) table shows 6771798025000004 as Mastercard but credit-card-type returns as Maestro.

Here is the failed test snippet:
```
    Expected: "Mastercard"
    Received: "Maestro"

      81 |       for (const cardNumber of testCards) {
      82 |         payment.update({cardNumber});
    > 83 |         expect(payment.cardType).toBe('Mastercard');
         |                                  ^
      84 |       };
```

**Comment by EJohnF** [comment]
Just face the same issue. @navarrojandg did you find something about this problem?

**Comment by crookedneighbor** [comment]
We'll bring it up with our cards team. It's possible that Mastercard has new bins but we were not made aware.

**Comment by crookedneighbor** [comment]
According to the Mastercard docs: https://www.mastercard.us/en-us/business/issuers/get-support/simplified-bin-account-range-table.html

The range `6771790000-6771799999` is marked as Maestro. 

I _think_ Adyen's test card is wrong here then. I'm going to close this for now, but if you can get us more information about why Adyen thinks that's a Mastercard bin range, feel free to comment here.
