### ISSUE TITLE
Incorrectly identifies card as maestro

### ISSUE THREAD

**Issue by pinal-r** [braintree/credit-card-type#123]
It was identifying Switch/Solo (Paymentech) | 6331101999990016 (https://www.paypalobjects.com/en_GB/vhelp/paypalmanager_help/credit_card_numbers.htm) card as Maestro so added validatons for switch and solo as below 

valid.creditCardType.addCard({
      niceType: 'Switch',
      type: 'switch',
      patterns: [4903, 4905, 4911, 4936, 564182, 633110, 6333],
      gaps: [4, 8, 12],
      lengths: [16, 18, 19],
      code: {
        name: 'CVV',
        size: 3,
      },
    });

valid.creditCardType.addCard({
      niceType: 'Solo',
      type: 'solo',
      patterns: [6334, 6767],
      gaps: [4, 8, 12],
      lengths: [16, 18, 19],
      code: {
        name: 'CVV',
        size: 3,
      },
    });

Now it correctly identifies as switch but now for card 6759649826438453 (http://support.worldpay.com/support/kb/bg/testandgolive/tgl5103.html) which is actually maestro it identifies as Switch. What is solution to this ? 
Same issue with 630495060000000000 which is actually laser but identifies are maestro.

**Comment by crookedneighbor** [comment]
I'm not able to reproduce your issue:

```
const cc = require("credit-card-type");

cc.addCard({
  niceType: 'Switch',
  type: 'switch',
  patterns: [4903, 4905, 4911, 4936, 564182, 633110, 6333],
  gaps: [4, 8, 12],
  lengths: [16, 18, 19],
  code: {
    name: 'CVV',
    size: 3,
  },
});

cc.addCard({
  niceType: 'Solo',
  type: 'solo',
  patterns: [6334, 6767],
  gaps: [4, 8, 12],
  lengths: [16, 18, 19],
  code: {
    name: 'CVV',
    size: 3,
  },
});

cc("6759649826438453") // type: 'maestro'
```

I don't see how `6759649826438453` would ever report to be a Switch card based on the Switch pattern you provided.

If you did:

```js
cc("67") // [type: 'maestro', type: 'solo']
```

Where Maestro has a higher priority, so in the `card-validator` module you're using, it only exposes the card number with the highest priority. You can change the priority with the `changeOrder`. See the docs here for adding card types: https://github.com/braintree/credit-card-type#adding-card-types

For Laser, you would need to add the card type first. Based on your example, it doesn't look like you are doing that.
