### ISSUE TITLE
Feature request: length-specific gaps

### ISSUE THREAD

**Issue by dospunk** [braintree/credit-card-type#133]
Right now, the `gaps` attribute can only have information for one number length, which isn't very useful for cards like Diner's Club, where their [14-digit cards](https://www.dinersclub.pl/images/karty/paypass/Karta_DC_LOT_CORPO_paypass.jpg) have one format while their [16-digit cards](https://www.dinersclubus.com/us/images/en/diners-club-corporate-carte-blanche.jpg) have another. 

My proposed solution would be to turn the `gaps` array into an object, like so
```js
{
    niceType: 'Diners Club',
    type: 'diners-club',
    patterns: [ [Array], 36, 38, 39 ],
    gaps: {
        14: [4, 10],
        16: [4, 8, 12]
        // If the gap pattern for a length is unknown then it could just be left out of the gaps object
    },
    lengths: [ 14, 16, 19 ],
    code: {
        name: 'CVV',
        size: 3
    },
    matchStrength: 3
}
```

**Comment by crookedneighbor** [comment]
Yeah, that sounds reasonable. It'll have to be a major version bump to accamodate the breaking change, but that shouldn't be a problem.

**Comment by SancSalix** [comment]
Thanks for reaching out! We've forwarded your request for evaluation and potential prioritization. We can't provide an ETA on if/when this would get added to the library. But in the meantime, if you'd like to submit a PR for your idea you are welcome to do so!

**Comment by SancSalix** [comment]
(also apologies for delay on ticketing this up)

**Comment by hollabaq86** [comment]
Closing this issue as we've directed this feature request to the appropriate folks for consideration of prioritization. As @SancSalix mentioned, if anyone wants to PR this feature, go for it!
