### ISSUE TITLE
does it include all card type. i have some more types ?

### ISSUE THREAD

**Issue by Deepanshusuman** [braintree/credit-card-type#134]
where are other cards like

      
	"Aura",
	"Bankcard",
	"Cabal",
	"China UnionPay",
	"Dankort",
	"Diners Club Carte Blanche",
	"Diners Club Enroute",
	"Diners Club International",
	"InstaPayment",
	"InterPayment",
	"Visa Electron",

i found these type in https://github.com/retgits/creditcard/blob/master/creditcard.go

do you have any plan for golang version?

**Comment by crookedneighbor** [comment]
We officially support the card types that Braintree Payments supports. For additional card types, we need official documentation from the provider about the bin ranges and other card details.

If there is a particular card type that you need that this module does not include by default, you can always add the type yourself following this documentation: https://github.com/braintree/credit-card-type#adding-card-types

If you have official documentation for any of the types above that are missing from this module, feel free to open a new issue with the documentation.
