### ISSUE TITLE
Master Cards starts with 2-series are shown as invalid

### ISSUE THREAD

**Issue by Sanketh1220** [braintree/credit-card-type#139]
### General information

- Library version:  9.1.0
- Chrome Version 96.0.4664.45 (64-bit) on Windows 11 

### Issue description
I have used it for card validation in one my project when am using with master card which starts with 2-series even when I enter a valid card it shows invalid.

**Comment by jplukarski** [comment]
Thanks for bringing this up, @Sanketh1220. Support for Mastercard 2-series should have been added in [version 6.1.1](https://github.com/braintree/credit-card-type/blob/main/CHANGELOG.md#611).

[Here is the pattern that we use to validate Mastercards](https://github.com/braintree/credit-card-type/blob/main/CHANGELOG.md#611). If you can provide us with official documentation from Mastercard that we need to add some ranges to our pattern then we can get this fixed. Feel free to also open up a PR citing any official Mastercard documentation. We'll leave this issue open in the meantime.

**Comment by hollabaq86** [comment]
Closing this since we haven't heard back from OP.
