### ISSUE TITLE
redundant types removal in union pay

### ISSUE THREAD

**Issue by Deepanshusuman** [braintree/credit-card-type#141]
in union pay you can remove 
622018 , [624 , 626]                                 =>    [623 , 626]
[622019 , 622999] ,[ 622126 , 622925]    =>    [622010 , 622999]
because right is the superset of left

**Comment by jplukarski** [comment]
@Deepanshusuman thanks for bringing this to our attention. We will add a task in our backlog to clean up these ranges. Feel free to also open a PR if you'd like to contribute.

We'll leave this open until we are able to prioritize and perform this work.
