### ISSUE TITLE
Maestro test cards from mangopay are identified as diners-club

### ISSUE THREAD

**Issue by rik** [braintree/credit-card-type#20]
3012340000000000 and 3012349999999999 are maestro test cards from Mangopay (see [Maestro tab in their docs](https://docs.mangopay.com/api-references/test-payment/))

This library is detecting them as `diners-club`. We've currently hardcoded those in our codebase but it would be nice to have this support here. I have no idea how test cards are generated and if there is some logic behind it so I can't provide a general patch.

**Comment by crookedneighbor** [comment]
Hey @rik, did some quick digging, and it looks like it's a problem on Mangopay's side, at least according to this issue: https://github.com/Mangopay/cardregistration-js-kit/issues/10#issuecomment-139519987

#### The question
> It is weird for the example number from Mangopay: 3012340000000000 it always tells me that it is a Diners-Card?

#### The response from mangopay
> yep, our PSP doesn't use the right BINs with their test cards unfortunately - it's on our list to sort out :-)
