### ISSUE TITLE
CVC/Code Location

### ISSUE THREAD

**Issue by blazedd** [braintree/credit-card-type#24]
Nearly all card brands place their security code on the back of the card. American Express, however, places this on the front of the card. Is there any plan to include this in the code object as well? This can be helpful for showing the correct diagram on "help".

![Example](https://cdn-images-1.medium.com/max/1000/1*xwVm5p5vidUBXwdCanwnrA.png)
image taken from https://uxdesign.cc/the-anatomy-of-a-credit-card-payment-form-32ec0e5708bb

**Comment by mrak** [comment]
That's an interesting idea. It's not quite as straightforward as Amex being on the front and others being on the back. Depending on the card, discover could have it on either side. In those cases maybe a `code.placement === 'either'` could suffice?

**Comment by crookedneighbor** [comment]
@blazedd Are you interested in opening a pull request for this?

**Comment by quinnjn** [comment]
@blazedd I think we all agree that this would be an awesome data point to have for this library, unfortunately we don't currently have the cycles to pick this requirement up. 

If anyone is interested, we'd love a PR for this in the future.

Closing until a PR comes through.
