### ISSUE TITLE
Credit Card Type is not checking the current card length

### ISSUE THREAD

**Issue by saxinte** [braintree/credit-card-type#27]
Basically this MasterCard number: **5100 0811 1222 3332**

If we use it this way:
creditCardType('5100081112223332**5100081112223332**'));
creditCardType('5100081112223332**1111**'));
creditCardType('5100081112223332**0000**'));

Found a MasterCard credit card which is wrong, it should test the length of the current card.

Thanks

**Comment by mrak** [comment]
We actually package a different library for validations such as length and Luhn 10: [card-validator](https://github.com/braintree/card-validator).

This one is for best-guess identification of a card type. The card-validator library should be able to account for your scenarios.

**Comment by crookedneighbor** [comment]
^ Makes sense to me.
