### ISSUE TITLE
MIR card type

### ISSUE THREAD

**Issue by imdkva** [braintree/credit-card-type#45]
Hi!

Just wanna ask if this has a chance to alive (i've commented there):
https://github.com/braintree/credit-card-type/pull/35

**Comment by crookedneighbor** [comment]
I've responded on the pull request.

**Comment by crookedneighbor** [comment]
v6.2.0 allows you to add custom card brands. See https://github.com/braintree/credit-card-type#adding-card-types for documentation.

**Comment by crookedneighbor** [comment]
We got official documentation for the Mir card type, and this has been released as part of v6.3.0
