### ISSUE TITLE
Add UMD/AMD support

### ISSUE THREAD

**Issue by lptn** [braintree/credit-card-type#46]
I know about [previous rejected proposal](https://github.com/braintree/credit-card-type/issues/10) to add UMD/AMD support, but the reasons are not clear for me.
This is a second attempt

**Comment by crookedneighbor** [comment]
Our position is still the same: https://github.com/braintree/credit-card-type/issues/10#issuecomment-236257754

> For now, we've decided to not add built in AMD support. If someone wants to fork and maintain an AMD compatible version of the library, we're open to adding a link to it in the README.
