### ISSUE TITLE
Other's card type

### ISSUE THREAD

**Issue by Minotti** [braintree/credit-card-type#57]
Hello, what kind of 'Elo' and 'Aura' cards are not supported? Would you implement them please?

**Comment by crookedneighbor** [comment]
I'm not familiar with those card types. Can you provide documentation for them?

**Comment by Minotti** [comment]
I'll look for it and when I find it I'll give it to you.

**Comment by Romanchuk** [comment]
Aura card is a mastercard. "Aura" is just a shop name.

**Comment by Romanchuk** [comment]
@crookedneighbor 
Please, add russian national bank card "MIR".
I couldn't find much info, the only thing i'am sure it starts from "2".
http://mironline.ru/business/#card-security
There is card type that i use to validate it:
```
const mirCardType = {
    niceType: 'МИР',
    type: 'mir',
    prefixPattern: /^2$/,
    exactPattern: /^2\d*$/,
    gaps: [4, 8, 12],
    lengths: [16, 19],
    code: {
      name: 'ППК2',
      size: 3
    }
```

**Comment by crookedneighbor** [comment]
@Romanchuk Until we can get official documentation around the MIR credit card type, we are not going to add it. See https://github.com/braintree/credit-card-type/pull/35

@Minotti I'm going to close this now, but if you can provide official documentation, please comment here with it.

**Comment by crookedneighbor** [comment]
v6.2.0 allows you to add custom card brands. See https://github.com/braintree/credit-card-type#adding-card-types for documentation.
