### ISSUE TITLE
Not all 2-series BIN MasterCard are covered by patterns

### ISSUE THREAD

**Issue by reest1685** [braintree/credit-card-type#62]
I have a 2-series MasterCard test card, BIN starts with _2239_. The `exactPattern` and `prefixPattern` don't include the above BIN.

According to [this MasterCard article](https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html), the range of 2-series is from 222100-272099. Then _2239_ should be included.

https://github.com/braintree/credit-card-type/blob/9ff00528b709a861ed702694156739d7695a441b/index.js#L56

**Comment by crookedneighbor** [comment]
Thanks for the report. You're right that the pattern is a little off. We'll get this fixed soon.

**Comment by crookedneighbor** [comment]
Released in v6.1.1
