### ISSUE TITLE
Support 13-digit Visa card length

### ISSUE THREAD

**Issue by reest1685** [braintree/credit-card-type#64]
Would you mind supporting `13` in `.lengths` of Visa card type?
_Verified by Visa_ **requires** testing for 13-digit Visa card.

https://github.com/braintree/credit-card-type/blob/2b36b2405ee1dd2dc9802db1553795d8dcb811c5/index.js#L45

**Comment by crookedneighbor** [comment]
13 digit visas are no longer in circulation, so it does not make sense to include them in this module. If it's a requirement for your use case, I recommend forking the library instead.

**Comment by crookedneighbor** [comment]
v6.2.0 allows you to adjust the configuration for card brands. See https://github.com/braintree/credit-card-type#adding-card-types for documentation.

**Comment by reest1685** [comment]
Great, @crookedneighbor .
