### ISSUE TITLE
[Feature] CardType from Brazil: Elo

### ISSUE THREAD

**Issue by luisibanhi** [braintree/credit-card-type#65]
### General information

* Library version: 6.0.0
* Browser and OS: Chrome 63.0.3239.132 (64-bit) on MacOS 10.13.2 

### Issue description

I'm from brazil, and here, we have a credit card type called "Elo", i want that type of card be accepted in this library ... so, i will send a pull request to this.

**Comment by crookedneighbor** [comment]
Closed as a duplicate of https://github.com/braintree/credit-card-type/issues/57 and https://github.com/braintree/credit-card-type/issues/60

**Comment by crookedneighbor** [comment]
See those issues for details
