### ISSUE TITLE
Mastercard is one word and `type` should not include a dash

### ISSUE THREAD

**Issue by frabonomi** [braintree/credit-card-type#69]
The `type` property for a Mastercard credit card should be `mastercard` instead of `master-card`, since it is one word. It looks like an inconsistency to me. The constant name is rightfully `MASTERCARD`, not `MASTER_CARD`.

Is there a reason why that's not following the same naming rules used for the other cards?

**Comment by crookedneighbor** [comment]
Previously, Mastercard's branding was `MasterCard`, so the enum followed the convenvtion. We'll update the enum in the next major version. I've added a TODO comment about it: https://github.com/braintree/credit-card-type/commit/c9b8439a459c9a68195ec9158ffcf186abfe4290

**Comment by frabonomi** [comment]
Ah great, thanks!
