### ISSUE TITLE
getTypeInfo does not return prefixPattern/exactPattern regular expressions 

### ISSUE THREAD

**Issue by jestanoff** [braintree/credit-card-type#77]
### General information

* Library version: 7.00
* Browser and OS: Chrome 68.0.3440.106 (64-bit) on MacOS 10.12.6 

### Issue description

My intended use case is to modify existing card type VISA, add additional length of 11 but change nothing else:
```
  const visa = creditCardType.getTypeInfo(creditCardType.types.VISA);
  creditCardType.addCard({
    ...visa,
    lengths: [11, ...visa.lengths],
  });
```
with the above code I'm getting the following error:
```
undefined is not an object (evaluating 'value.exactPattern.test')
          creditCardType@webpack:///node_modules/credit-card-type/index.js:186
```

If I include `prefixPattern/exactPattern` e.g.
```
  const visa = creditCardType.getTypeInfo(creditCardType.types.VISA);
  creditCardType.addCard({
    ...visa,
    prefixPattern: /^4$/,
    exactPattern: /^4\d*$/,
    lengths: [11, ...visa.lengths],
  });
```
That issue is solved, still these properties shouldn't be overrided manually as they might change in feature releases of the package.

I narrowed down the issue in the clone() method that is using `JSON.stringify` to clone the types. RegEx object cannot be cloned with this method.
https://github.com/braintree/credit-card-type/blob/master/index.js#L37

**Comment by crookedneighbor** [comment]
We also intentionally remove the properties: https://github.com/braintree/credit-card-type/blob/e8c0125969bf4e07b2c442137d5e1cbc7f10023a/index.js#L38-L39

Thanks for bringing this up. I think it'd probably best to include an `updateCard` method that allows you to modify the existing one, rather than trying to merge it.

**Comment by jestanoff** [comment]
Fair point, it is a feature request then. Thank you!

**Comment by crookedneighbor** [comment]
https://github.com/braintree/credit-card-type/pull/78
