### ISSUE TITLE
Publish new version in npm

### ISSUE THREAD

**Issue by isacjunior** [braintree/credit-card-type#84]
### General information

* Library version: 8.0.0

### Issue description

The latest version in npm is 8.0.0, this version doesn't have last commit. The npm description mentioned that lasted version published 3 mounts ago, but the last commit was committed 4 days ago.
 
Last commit: https://github.com/braintree/credit-card-type/commit/2069bc40fa218b1541ef41fd0d8d5a048fd196ed

**Comment by crookedneighbor** [comment]
Are you in need of the hiper and hipercard card types? That's the only feature difference between what's on master and v8.0.0

**Comment by isacjunior** [comment]
Yes, I need hiper and hipercard types.

**Comment by crookedneighbor** [comment]
Released in v8.1.0
