### ISSUE TITLE
Feature request: Check whether input is likely a credit card

### ISSUE THREAD

**Issue by niftylettuce** [braintree/credit-card-type#90]
Similar to https://github.com/kevva/credit-card-regex, but instead it would convert the input to digits only, and then check if the length matches a possible length of the given cards, and returns `true` or `false`.

**Comment by niftylettuce** [comment]
I came up with this (untested):

```js
function isCreditCard(val) {
  const digits = val.replace(/\D/g, '');
  const types = creditCardType(digits);
  if (!isArray(types) || isEmpty(types)) return false;
  let match = false;
  for(let t=0; t<types.length; t++) {
    if (match) break;
    const type = types[t];
    // can match any one of the lengths
    if (!isArray(type.lengths) || isEmpty(type.lengths)) continue;
    for(let l=0; l<type.lengths.length; l++) {
      const len = type.lengths[l];
      if (isFinite(len) && len === digits.length) {
        match = true;
        break;
      }
    }
  }
  return match;
}
```

**Comment by demerino** [comment]
@niftylettuce Thanks for the suggestion. We'll keep this in mind and feel free to create a PR with your proposed solution if you like.

**Comment by niftylettuce** [comment]
Here's my usage and complete working code: https://github.com/cabinjs/parse-request/blob/master/src/index.js#L21-L42

It parses the string argument input to digits only, and then checks if that itself is a credit card match by itself.

**Comment by crookedneighbor** [comment]
In my opinion, this looks more like the domain of https://github.com/braintree/card-validator, which uses credit-card-type under the hood.

Going to close this.
