### ISSUE TITLE
Code's name doesn't actual for card brand "MIr" in readme

### ISSUE THREAD

**Issue by oalipina** [braintree/credit-card-type#91]
In file [README.md](https://github.com/braintree/credit-card-type/blob/2069bc40fa218b1541ef41fd0d8d5a048fd196ed/README.md) we have table card brands with security codes. For brand "Mir" incorrect name of code. In table name "CVP" but in  [code](https://github.com/braintree/credit-card-type/blob/2069bc40fa218b1541ef41fd0d8d5a048fd196ed/lib/card-types.js#L192) name is "CVP2"
![image](https://user-images.githubusercontent.com/26428684/56881034-bb6a6a80-6a67-11e9-95ac-dd5a599e94f5.png)
![image](https://user-images.githubusercontent.com/26428684/56881042-c7562c80-6a67-11e9-9bb7-9c643f72de49.png)

**Comment by crookedneighbor** [comment]
Thanks for the report! This is fixed now.
