### ISSUE TITLE
Missing 8 series bin range for UnionPay

### ISSUE THREAD

**Issue by leebradley** [braintree/credit-card-type#95]
### General information

* Library version: 8.2.0
* Browser and OS: Any

### Issue description

Announcement from the [Vantiv processor website](http://info.vantiv.com/rs/048-BUR-972/images/July%202018%20Enterprise%20Advantage%20Bulletin.html):

> China Union Pay is launching a new 8 Series BIN range. Merchants and partners should ensure all point-of-sale devices are ready to identify, accept, and process these new BINs by October 12, 2018. The 8 Series Cards are expected to begin appearing in the market January 2019.
>
>Start|End|Issuing Network
> -- | -- | --
> 81000000 | 81099999 | UnionPay
> 81100000 | 81319999 | UnionPay
> 81320000 | 81519999 | UnionPay
> 81520000 | 81639999 | UnionPay
> 81640000 | 81719999 | UnionPay

Looks like there is support for 6 series, but 8 has not been added yet.

**Comment by crookedneighbor** [comment]
Thanks for the info, we'll look into this. (feel free to open a PR if you need it sooner)

**Comment by leebradley** [comment]
@crookedneighbor Sounds good! Submitted a PR with the changes and some tests to validate the ranges.
